### ISSUE TITLE
Components of Homepage

### ISSUE THREAD

**Issue by shashank-sharma** [Technical-NGO/Technical-NGO.github.io#17]
I am creating this issue so that we can finalize the structure of this page. I want you all to give some suggestions like what we need to put in our homepage. It can be anything, I will edit this and start adding as checkbox which will later become issues.

We will start with alpha release as our milestone. After completing all the pages we will start working on our beta version of site by testing and removing bugs and then we will release our stable site which will have no bug.

## Components:

- [x] Introduction - What we are and what we do
- [x] About - Get in touch with us
- [x] Navigation Bar - Simple Navigation
- [x] Footer - Made with love
- [x] Images/Logos - To be put with content (If we are planning)

After finalizing this we will start creating homepage and start contributing it.

*Note: While making pull request please mention this issue in your pull request so that we can check the status of this issue and based on this we will move ahead.

**Comment by aravindharinair** [comment]
@shashank-sharma here's two:
1. A short brief of our organization and what we are working towards (the README could be modifed for this.
2. A "How to Get in Touch with Us" sub for letting us know if there'd be some work that we're willing to take up.

**Comment by aravindharinair** [comment]
@Technical-NGO/general :
Guys, do contribute. At least we can start the work on the homepage. Lack of participation defeats the objective of this community.
I can see that there are 41 members here but hardly 15 people have responded **in any thread**. If it is because you think you don't have the necessary experience to contribute here, I have only one thing to say: " *Look at ME !* ". I started FED only a couple of months prior to this and even though I cannot contribute much in the technical sense (yet), I can provide input in other areas and that's what I do. And I can see from your GitHub repos that there are people here who are more experienced than me, becoming silent spectators. Why, may I ask???
Remember that this community was created for us to gain experience from working and that objective cannot be realized until and unless everyone actively participates in the community. So, everyone, please do contribute to this. And no, don't say you were "trying" to contribute. As Master Yoda says, "Do or do not, there is no try". 
Peace! :vulcan_salute:

**Comment by Prateek-Tewari** [comment]
@shashank-sharma 
Please find the comments inline and reply
 Introduction - What we are and what we do(Is this going to be a separate page?)
 About - Get in touch with us(This one should be a separate page,correct me if I am wrong)
 Navigation Bar - Simple Navigation( Please elaborate simple?)
 Footer - Made with love( Something with a 💓,I have seen this lately in few websites footer. Will it be minimal?)
 Images/Logos - To be put with content (If we are planning - Is someone working on logos?)
Is anyone proficient with wireframes,if yes,then that person can step forward and guide us at least about how do we put our ideas into action,the requirements will be more clear if we get a wireframe or if we can get some resource to learn wireframe from.

**Comment by strider99** [comment]
something like this? its a very simple page. easy to create. gradually we
can move to more complex ui.
For now, we can create it and try to make it responsive using media queries
without using bootstrap or any other css-grid library.

**Comment by MorphyMeri** [comment]
First let us create a page and summarize then let us create branch for each page and work on it 
**Home Page structure-**
Header section (Home , About us, Projects, Contact us)
Welcome section (A nice welcome message or a quote with some background)
Who are we ? or About us (section) 
Our Vision Section
Footer 

After creating this lets add **know more button** to every section and then redirect to the designated page but first let is create a home page and then work on individual pages.

Header buttons should navigate in the home page itself (the navigation can be changed later to individual pages once everything is done) . And the know more button in the each section should navigate to the individual page (Till everything is done). 

Now i need some one to take time for writing the content or modifying the readme file . And create a new file , name it as content and request a pull.

Content and writing code for page is important. Links , Logos, background color, etc, can be added at any point of time so dont waste time on it. Just add some temporary image and color if you need to , we can change it later once the logo is done.

 **_This is just my idea. Feel free to give any suggestions._**

**Comment by Karthik781** [comment]
@shashank-sharma  @MorphyMeri  I am ready to take up the header section and will start building a static header part containing Home, About us, projects, Contact us as for now. Any suggestions on how it should  look like?

**Comment by harsh8199** [comment]
@shashank-sharma Apart fron the HTML , i think we shud first create a basic design, some css template kind of thing that  every one can then manipulate as required by different pages of our website.

**Comment by Praveen-Sharma7204** [comment]
All right !

<Header> :  Home , Who Are we? , What We do? , Expo (or) Portfolio , Contact Us

**Comment by shashank-sharma** [comment]
Hi guys, I was busy for past few days as I was traveling but now I am available. One thing please note is that you guys can't make Pull Request without opening any issue. Also right now we didn't even decided whether we are going use framwork or not. There are so many things which are not decided and happening in random. So please work in an organize way. @kundanvishen I want to get final announcement about the technical stack so that I can step up and divide the work like framework thing. According to this issue I have finalized all the component for home page but for other pages I am not able see any progress.

We need proper organization right now else I won't be able to handle it.

**Comment by aravindharinair** [comment]
I believe most of the initial milestones are met. Now we need to make it better. Especially the text.
@shashank-sharma , what's your opinion on marking all these complete?
P.S. I haven't added the "With :heart: "
Gotta add that next...

**Comment by strider99** [comment]
i am ready.

**Comment by shashank-sharma** [comment]
@aravindharinair Thanks for reminding me. Yes the homepage is done already and completing all the basic requirements. Hence closing this issue
