### ISSUE TITLE
Decide Organisation name

### ISSUE THREAD

**Issue by kundanvishen** [Technical-NGO/Technical-NGO.github.io#9]
Let's move all the discussion related to organisation name selection here.

**Comment by fayazara** [comment]
Have a look at these https://github.com/Technical-NGO/Technical-NGO.github.io/issues/2#issuecomment-366458920

**Comment by kundanvishen** [comment]
Suggested by @fayazara 

- UnderScore Lab
- Code for Hungry
- CodeWink
- Code Craft
- Angled Brackets
- Stash :-D
- CodeRewind
- Beginnera
- Equilibrium
- AlteredCode (inspired from Altered Carbon)
- Einsteinic
- Beginners_Lab

I'll be updating this list as often as possible.

**Comment by Prateek-Tewari** [comment]
•CodeSage
•CodingAngel
•CodeForThought
•CodeKarma
•CodeLens
•CharityCode or CodeCharity
•CodeNameHappy
•TheIndianCode
•HelpingHands
•HappyArena
•CodeNextDoor
•CodingLeague
•HopeGroup
•CodeSociety

**Comment by Prateek-Tewari** [comment]
•Skill Central
•Open Help
•Help Hub
•People's Coders
•Change World

**Comment by seeni-dev** [comment]
@kundanvishen Stash looks promising...

**Comment by djdj1992** [comment]
Yeah I liked the name Stash

**Comment by kundanvishen** [comment]
I've created the poll with the above-suggested names.

Vote your choice here:
[https://kundan.me/polls/organization-name.html](https://kundan.me/polls/organization-name.html)

Suggestion before voting:
A good name should reflect the value and the vision of the organization. A funky name with no correlation to what the organization is about would look weird to me.
But that's just how I feel.
You are free to vote whatever you agree with.

**Comment by awenits** [comment]
Well as this is mostly related to web development, i think title should include something for that. Also it should be related to GoogleScholars.. something like that..!

**Comment by awenits** [comment]
what about including some words like GoogleScholars, WebGeeks, WebEnthusiasts, Webers..?

**Comment by aravindharinair** [comment]
@awenits 
1. I fail to see the point in naming it Google Scholars. Because Google Scholars is an already existing service provided by Google for looking up research papers and other scholarly articles. - [Link](https://scholar.google.com) .
2. The names needn't have the word "Web" specifically in it. Might convey what we are doing but doesn't make the name sound good. At least that's what I feel. Go to the poll posted above, hit view, scroll down and read the comment posted there regarding using "Code" in the name.

**Comment by irshad2809** [comment]
guys not to disrespect or anything but before suggesting a name try googling it once .(i didnt found softer words , sorry)

**Comment by utkarsh2102** [comment]
@awenits : I think we should not include anything which already exists. 
Also, it might land us in trouble. Before using "Google", etc, we need a written permission regarding the same. We can't use something which is not ours. General things can for sure be used. But not the names of organisations pre-existing. 
Also, one must follow the laws before finalising the name.
No offence, please :)

**Comment by Praveen-Sharma7204** [comment]
How about Code::Studio()  ?

**Comment by aravindharinair** [comment]
@Praveen-Sharma7204 , not to get your hopes down, but:
Studio.code.org is a site.
And Visual Code Studio is an IDE by Microsoft.
Also, there's  http://code-studio.com ...

**Comment by hirenbhanushali** [comment]
Altered Code is a great choice, let's select it and finalize, before we lose this domain 😅

**Comment by irshad2809** [comment]
Yes. Altered code can be used

**Comment by aravindharinair** [comment]
@hirenbhanushali & @irshad2809 , nope. Lost that too... :cry:
[Altered Code Brewing](http://www.alteredcodebrewing.com/) seems like a brewery.
 Since their name is AlteredCodeBrewing, we might be able to use just the AlteredCode part, but those are legal issues which I have no idea about...

**Comment by harsh8199** [comment]
@kundanvishen  How about codeBand or Codeclan or codorg (inpired by codrops) ?

**Comment by kundanvishen** [comment]
@harsh8199  All the names you suggested are already owned by businesses. :(

**Comment by harsh8199** [comment]
@kundanvishen that is one hell of a coincidence.

**Comment by jibin2706** [comment]
Decided?

**Comment by kundanvishen** [comment]
Going ahead with the current name
